export ZDOTDIR=$HOME/.config/zsh
export PATH=$HOME/.local/bin/scripts/:$PATH
export PATH=$HOME/.local/bin/scripts/statusbar:$PATH
export PATH=$HOME/.cargo/bin/:$PATH
export PATH=$HOME/racket/bin:$PATH
export PATH=~/.local/bin:$PATH
export EDITOR=openemacs
export FILE=ranger
export BROWSER=firefox
export MYDATA=$HOME/.local/share/promnesia
export WORKON_HOME=$HOME/venv
export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
